# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "spree-bootstrap"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Hanley"]
  s.date = "2013-02-17"
  s.description = "A theme for spreecommerce using twitter's bootstrap based on Andrewmp1's spree_bootstrap_theme"
  s.email = "jack@cagedmedia.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/admin/spree_bootstrap_theme.js",
    "app/assets/javascripts/store/product.js",
    "app/assets/javascripts/store/spree_bootstrap_extras.js",
    "app/assets/javascripts/store/spree_bootstrap_theme.js",
    "app/helpers/spree/base_helper_decorator.rb",
    "app/overrides/add_class_to_thumbnails.rb",
    "app/overrides/add_classes_to_checkout_address_form.rb",
    "app/overrides/add_classes_to_product_listings.rb",
    "app/overrides/fix_header.rb",
    "app/overrides/replace_body.rb",
    "app/overrides/replace_checkout_edit_form.rb",
    "app/overrides/replace_product_show.rb",
    "app/views/spree/home/index.html.erb",
    "app/views/spree/overrides/_checkout_edit.html.erb",
    "app/views/spree/overrides/_replace_body.html.erb",
    "app/views/spree/overrides/_replace_home.html.erb",
    "app/views/spree/overrides/_replace_product_show.html.erb",
    "app/views/spree/shared/_head.html.erb",
    "app/views/spree/shared/_store_header.html.erb",
    "lib/spree-bootstrap.rb",
    "test/helper.rb",
    "test/test_spree-bootstrap.rb"
  ]
  s.homepage = "http://github.com/JHanley85/spree-bootstrap"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A theme for spreecommerce using twitter's bootstrap based on Andrewmp1's spree_bootstrap_theme"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

